<template>
    <div class="news-header news-header-image" v-if="headerImage" :style="headerImage">

    </div>
    <div class="news-header news-header-autogenerated flex-center" :style="bg" v-else>
        <div class="news-header-logo bg-center" :style="logo"></div>
    </div>
</template>

<script>
import { logoBackground } from "@/utils/theme-styles";
import { resizedImage } from "@/utils/images";

export default {
    name: "NewsHeader",
    props: ["headerImage", "theme"],
    computed: {
        bg() {
            if (!this.theme) return {};
            return logoBackground(this.theme);
        },
        logo() {
            if (!this.theme) return {};
            return resizedImage(this.theme, ["default_wordmark", "default_logo"], "h-300");
        }
    }
};
</script>

<style scoped>
    .news-header {
        padding-top: calc(100% / 3);
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
        margin: 16px 0;
        box-shadow: 0 0 4px 0px rgb(0 0 0 / 50%);
        background-color: #333;
    }
    .news-header.news-header-autogenerated {
        padding-top: calc(100% / 6);
        position: relative;
    }
    .news-header-logo {
        width: 50%;
        height: 90%;
        position: absolute;
        top: 5%;
        background-size: contain;
    }
</style>
