export default [
    { path: "", component: () => import("@/views/sub-views/event/EventMain.vue") },
    { path: "rosters", component: () => import("@/views/sub-views/event/EventRosters.vue") },
    { path: "bracket", component: () => import("@/views/sub-views/event/EventBrackets.vue") },
    { path: "brackets", redirect: "bracket" },
    { path: "schedule", component: () => import("@/views/sub-views/event/EventSchedule.vue") },
    { path: "matches", redirect: "schedule" },
    // { path: "scenarios", component: EventScenarios },
    { path: "scenarios", component: () => import("@/views/sub-views/event/EventScenarios2.vue") },
    { path: "draft", component: () => import("@/views/sub-views/event/EventDraft.vue") },
    { path: "staff", component: () => import("@/views/sub-views/event/EventStaff.vue") },
    { path: "about", component: () => import("@/views/sub-views/event/EventAbout.vue") },
    { path: "standings", component: () => import("@/views/sub-views/event/EventStandings.vue") },
    { path: "theme", component: () => import("@/views/sub-views/ThingTheme.vue") },
    { path: "brands", component: () => import("@/views/sub-views/event/EventBrands.vue") },
    { path: "auction", component: () => import("@/views/sub-views/event/EventAuction.vue") },
    { path: "stream", redirect: "streams" },
    { path: "stream-details", redirect: "streams" },
    { path: "streams", component: () => import("@/views/sub-views/event/EventStreamDetails.vue") }
];
